// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for sponsors documents */
interface SponsorsDocumentData {
  /**
   * Slice Zone field in *sponsors*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsors.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<SponsorsDocumentDataSlicesSlice>;
}
/**
 * Slice for *sponsors → Slice Zone*
 *
 */
type SponsorsDocumentDataSlicesSlice = SponsorSlice;
/**
 * sponsors document from Prismic
 *
 * - **API ID**: `sponsors`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SponsorsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SponsorsDocumentData>,
    "sponsors",
    Lang
  >;
export type AllDocumentTypes = SponsorsDocument;
/**
 * Primary content in Sponsor → Primary
 *
 */
interface SponsorSliceDefaultPrimary {
  /**
   * logo field in *Sponsor → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.primary.logo
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismic.ImageField<never>;
  /**
   * link field in *Sponsor → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.primary.link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField;
}
/**
 * Default variation for Sponsor Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SponsorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SponsorSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Sponsor*
 *
 */
type SponsorSliceVariation = SponsorSliceDefault;
/**
 * Sponsor Shared Slice
 *
 * - **API ID**: `sponsor`
 * - **Description**: `Sponsor`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SponsorSlice = prismic.SharedSlice<
  "sponsor",
  SponsorSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig
    ): prismicClient.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      SponsorsDocumentData,
      SponsorsDocumentDataSlicesSlice,
      SponsorsDocument,
      AllDocumentTypes,
      SponsorSliceDefaultPrimary,
      SponsorSliceDefault,
      SponsorSliceVariation,
      SponsorSlice,
    };
  }
}
