// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  event_gallery_card: dynamic(() => import("./EventGalleryCard")),
  facebook_events: dynamic(() => import("./FacebookEvents")),
  heading: dynamic(() => import("./Heading")),
  hero: dynamic(() => import("./Hero")),
  nav_bar_link: dynamic(() => import("./NavigationItem")),
  newsletter: dynamic(() => import("./Newsletter")),
  page_text: dynamic(() => import("./Text")),
  past_team: dynamic(() => import("./PastTeam")),
  phil_event: dynamic(() => import("./PhilEvent")),
  side_content: dynamic(() => import("./SideContent")),
  sponsor: dynamic(() => import("./Sponsors")),
  sponsor_deals: dynamic(() => import("./SponsorDeals")),
  stats: dynamic(() => import("./Stats")),
  team_member: dynamic(() => import("./TeamMember")),
};
