// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  facebook_events: dynamic(() => import("./FacebookEvents")),
  heading: dynamic(() => import("./Heading")),
  hero: dynamic(() => import("./Hero")),
  nav_bar_link: dynamic(() => import("./NavigationItem")),
  page_text: dynamic(() => import("./Text")),
  past_team: dynamic(() => import("./PastTeam")),
  sponsor: dynamic(() => import("./Sponsors")),
  stats: dynamic(() => import("./Stats")),
  team_member: dynamic(() => import("./TeamMember")),
};
